---
- name: copyweb
  hosts: 172.31.19.144
  become: yes

  vars:
    source_file: /opt/playbooks/webapp/target/webapp.war
    destin_file: /opt/tomcat/webapps


  tasks:
  - name: install java
    yum: name=java  state=latest



  - name: download tomcat
    get_url:
          url: https://apache.paket.ua/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat-10.0.4.tar.gz
          dest: /usr/local


  - name: extract
    unarchive:
           src: /usr/local/apache-tomcat-10.0.4.tar.gz
           dest: /usr/local
           remote_src: yes

   # - name: start tomcat
   # shell: nohup /usr/local/apache-tomcat-10.0.4/bin/startup.sh

  - name: Tomcatservers
    copy:
          src: "{{ source_file }}"
          dest: "{{ destin_file }}"
          backup: yes


